spec: ensure selinux-policy-targeted is installed
It may happen that the ovirt-vmconsole packages are installed
through kickstart, or, any way, alongside selinux-policy packages.
In this case, we must make sure the selinux-policy-targeted package
is installed before ovirt-vmconsole is, otherwise we could face errors
like

Failed to resolve booleanif statement at /etc/selinux/targeted/tmp/modules/
400/ovirt_vmconsole/cil:588
semodule:  Failed!
[...]
libsemanage.semanage_read_policydb: Could not open kernel policy
/etc/selinux/targeted/active/policy.kern for reading. (No such file or
directory).
OSError: No such file or directory

This error is never seen when installing the package on one existing
system (e.g. CentOS) because selinux-policy is part of the basesystem.

Change-Id: Id71c0a22b2bac8714743a2272616b76dff3d8490
Bug-Url: https://bugzilla.redhat.com/1463584
Signed-off-by: Francesco Romani <fromani@redhat.com>